### ISSUE TITLE
Detect Vivaldi

### ISSUE THREAD

**Issue by Cog-g** [donatj/PhpUserAgent#21]
Hi, what about the new Vivaldi browser? 

The string is: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Vivaldi/1.0.83.38 Safari/537.36 and is identified as Chrome 40.

**Comment by donatj** [comment]
#22 Added this.
