### ISSUE TITLE
Fatal error on function name "$find" in PHP 5.4 with eAccelerator

### ISSUE THREAD

**Issue by vatavale** [donatj/PhpUserAgent#24]
Fatal error: Function name must be a string in UserAgentParser.php on line 95
`$find('Playstation Vita', $key)`

**Comment by vatavale** [comment]
Im's sorry.Tthis problem persist only with eAccelerator.

**Comment by donatj** [comment]
eAccelerator doesn't appear to support anonymous functions, if you see here: https://github.com/eaccelerator/eaccelerator/issues/12 and it would appear that no work has been done on eAccelerator in almost 3 years and it's basically dead.

I'd suggest trying a different opcache engine that's better maintained.
