### ISSUE TITLE
Windows Phone wrong detection

### ISSUE THREAD

**Issue by tapule** [donatj/PhpUserAgent#25]
Hi,
This UA is from a Nokia Lumia Windows Phone:
"Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 920; Vodafone ES) like iPhone OS 7_0_3 Mac OS X AppleWebkit/537 (KHTML, like Gecko) Mobile Safari/537"
But it is detected as:
System: Android
Name: IEMobile
Version: 11.0

I think that the problem is in the call to "array_intersect($priority, $result['platform'])" who give priority to Android over Windows Phone.

Any solution to this??

**Comment by donatj** [comment]
Hah, that is one awful user agent string.  Luckily nothing but Xbox claims to be Windows Phone so as you guessed we can prioritize it, just needs to be behind Xbox and Xbox One.

I have pushed the update, added your user agent as a test, and posted a new release with the problem fixed - https://github.com/donatj/PhpUserAgent/releases/tag/v0.3.6

Thanks for the ticket!
