### ISSUE TITLE
Suggestion: detect bots

### ISSUE THREAD

**Issue by lucaferrario** [donatj/PhpUserAgent#26]
This PHP function is simply awesome! It only misses bot detection...it would be so nice to add platform type "bot" and browser types "googlebot", "bingbot", "yahoo slurp", etc... ;-)

**Comment by donatj** [comment]
They don't really have anything in common that I can grab onto, so it would require a hard coded list of "bots".  That's not really practical at this point while still trying to keep this thing minimal I'm afria.d

**Comment by lucaferrario** [comment]
In my website I added a check to know if the client is a bot or not. After calling parse_user_agent, if $user_agent['platform'] is NULL I just run this regex, which seems reliable to detect all the major bots (considering that it is run after user agent failed, false positive are almost impossible). I paste it here in case it can be useful :-)
preg_match('/bot|crawl|slurp|spider|cloudflare/i', $_SERVER['HTTP_USER_AGENT'])

**Comment by luigifab** [comment]
(Now) there are some bots in _Currently Detected Browsers_.
```php
echo $ua->platform() . PHP_EOL;
echo $ua->browser() . PHP_EOL;
echo $ua->browserVersion() . PHP_EOL;
```
Is it possible to add `$ua->isBot()`?

**Comment by donatj** [comment]
@luigifab Per the README, 

> This is not meant as a browser "knowledge engine" but rather a simple parser. Anything not adequately provided directly by the user agent string itself will simply not be provided by this.

https://github.com/donatj/PhpUserAgent#what-it-does-not-do

There is no _reliable way_ to know if something is a bot or not without maintaining a list of UA's known to be bots.

@lucaferrario 's method of checking if the platform is null may or may not be good enough for your purposes, but it's not reliable enough to codify.
