### ISSUE TITLE
Edge?

### ISSUE THREAD

**Issue by am-cego** [donatj/PhpUserAgent#28]
How about the new Edge browser? :-)

Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by donatj** [comment]
That currently parses to IE12 which is correct because as to my understanding they are the same browser with different window dressing. 

I don't have Windows 10 yet but according to the documentation it appears they use the same user agent in which case there is no way to tell them apart. That said I will try and get my hands on it later in the week to experiment.

**Comment by am-cego** [comment]
Thank you for you quick reaction!

Edge is a new browser. The rendering engine is new (EdgeHTML), and Windows 10 has both IE11 and Edge installed - with Edge set as the default browser.

The IE11 user agent string on my Windows 10 is:
Mozilla/5.0 (Windows NT 10.0; Trident/7.0; rv:11.0) like Gecko.

Hope that helps!

**Comment by patrickkettner** [comment]
@donatj just wanted to chime in that there is no such thing as IE 12. IE 11 is the last version of IE

**Comment by donatj** [comment]
@patrickkettner reading, this is a change. There was going to be a 12 and Edge, at the time Spartan, and they were going to share the rendering engine, but it looks like this isn't happening.

**Comment by patrickkettner** [comment]
Hmmm... I have never hear quite that before. What's happening is IE 11 is
still going to be around for enterprise customers and legacy sites that are
using non standard technology that cannot be upgraded. For them, IE will
not disappear and will get bare bones/security updates. Edge is a new
browser that was built with some pieces of IEs engines, but a huge chunk of
it is new.

**Comment by donatj** [comment]
Micorosft finally put the edge VMs back up.  I should be getting to this real quick now.

**Comment by donatj** [comment]
https://github.com/donatj/PhpUserAgent/releases/tag/v0.4.0  The latest release, v0.4.0 resolves this.
