### ISSUE TITLE
Needing platform information

### ISSUE THREAD

**Issue by gokhanege** [donatj/PhpUserAgent#29]
Hi Jesse,

I think requiring the platform type for example Mobile or Desktop.

**Comment by jjui** [comment]
Saw this open issue, would love the ability too - as to target all possible medias with title `Desktop / Mobile or Console` would be simplicity to the max. So +1 on this one.

**Comment by maoxiong** [comment]
+1 here too

**Comment by Firegarden** [comment]
I came to open an issue specifically so I could as for platform type for example Mobile or Desktop or Tablet or Other.

Guys can we not put our heads together and get a variable going to return this value?

Thank you

**Comment by donatj** [comment]
I'm closing this as I have been sitting on it for 4 years and still have no plans on implementing it.
