### ISSUE TITLE
Move the function to a class

### ISSUE THREAD

**Issue by ThaDafinser** [donatj/PhpUserAgent#33]
Hi,

is it possible that you move your function inside a class / method?

With the function only approach, i have a lot of problems in case of testing / mocking.

**Comment by donatj** [comment]
Maybe in a major release a while down the road, but not now as there is a pretty big install base and I don't want to break compatibility.  

That said, if you inject the user agent parser as a callable it should be perfectly testable/mockable.

So lets say I'm using it in this class and I want to test `doUserAgentStuff`

```php
<?php

class ClassIWantToTestUsingPhpUserAgentInjection {

	/** @var callable */
	protected $userAgentParser;

	public function __construct( callable $userAgentParser ) {
		$this->userAgentParser = $userAgentParser;
	}

	function doUserAgentStuff() {
		$ua     = $this->userAgentParser;
		$result = $ua();

		switch( $result['platform'] ) {
			case 'Linux':
				return 1;
			case 'Macintosh':
				return 2;
		}

		return 3;
	}

}
```

I can test it very easily as follows:

```php
<?php

class ClassIWantToTestUsingPhpUserAgentInjectionTest extends \PHPUnit_Framework_TestCase {

	public function test_doUserAgentStuff() {
		$inst = new \ClassIWantToTestUsingPhpUserAgentInjection(function () { return [ 'platform' => 'Linux' ]; });
		$this->assertSame(1, $inst->doUserAgentStuff());

		$inst = new \ClassIWantToTestUsingPhpUserAgentInjection(function () { return [ 'platform' => 'Macintosh' ]; });
		$this->assertSame(2, $inst->doUserAgentStuff());

		$inst = new \ClassIWantToTestUsingPhpUserAgentInjection(function () { return [ 'platform' => 'Windows' ]; });
		$this->assertSame(3, $inst->doUserAgentStuff());
	}

}

```

When I want to create a normal instance of my class, I just instantiate it like so:

```php
$inst = new ClassIWantToTestUsingPhpUserAgentInjection('\\parse_user_agent'));
```

**Comment by ThaDafinser** [comment]
Thank you for the input @donatj 

I've "mocked" it a bit different, but also worked in my case https://github.com/ThaDafinser/UserAgentParser/blob/master/tests/unit/Provider/DonatjUAParserTest.php#L12


But in `cannot test` this line, since the function is always loaded through composer on init
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/DonatjUAParser.php#L44

**Comment by ThaDafinser** [comment]
@donatj this is the only part i'm not able to test currently. Any idea?

![image](https://cloud.githubusercontent.com/assets/533017/11712687/f8756fb8-9f2e-11e5-9a81-051826c6ff96.png)
