### ISSUE TITLE
Add Platform Version

### ISSUE THREAD

**Issue by tmfksoft** [donatj/PhpUserAgent#37]
It'd be great to gather the platform version where possible.
Such as "Windows 10", and for extra brownie points browser version too.

I'd love to see this added.

Thanks!

**Comment by donatj** [comment]
See the OS Version section of the README ;)

**Comment by tmfksoft** [comment]
Oops, didn't notice that.
Tired 5am coding sessions are fun, you end up missing all the docs! :P

**Comment by ToX82** [comment]
dding the windows version

**Comment by ToX82** [comment]
Obtaining the windows version only is pretty simple though.

        $parser = new \donatj\UserAgent\UserAgentParser();
        $detect = $parser->parse();

        $platform = $detect->platform();

        if ($platform === 'Windows') {
            $userAgent = $_SERVER['HTTP_USER_AGENT'];

            if (strpos($userAgent, ' NT 6.2;') !== false) {
                $platform .= ' 8';
            } elseif (strpos($userAgent, ' NT 6.3;') !== false) {
                $platform .= ' 8.1';
            } elseif (strpos($userAgent, ' NT 10.0;') !== false) {
                $platform .= ' 10';
            } elseif (strpos($userAgent, ' NT 6.1;') !== false) {
                $platform .= ' 7';
            } elseif (strpos($userAgent, ' NT 6.0;') !== false) {
                $platform .= ' Vista';
            } elseif (strpos($userAgent, ' NT 5.1;') !== false) {
                $platform .= ' XP';
            } elseif (strpos($userAgent, ' NT 5.0;') !== false) {
                $platform .= ' 2000';
            }
        }
