### ISSUE TITLE
What about rendering engine?

### ISSUE THREAD

**Issue by garrettw** [donatj/PhpUserAgent#39]
What do you think about grabbing the rendering engine (Gecko/WebKit/Blink/etc) and putting that in the output array as well, maybe with a key of `engine`?

**Comment by donatj** [comment]
I added a little note to the readme:

>This is not meant as a browser "knowledge engine" but rather a simple parser. Anything not adequately provided directly by the user agent string itself will simply not be provided by this.

rendering engine falls into this category. It largely requires knowledge not provided by the user agent string.
