### ISSUE TITLE
doubt about an if

### ISSUE THREAD

**Issue by zephirfan** [donatj/PhpUserAgent#49]
https://github.com/donatj/PhpUserAgent/blob/3b4a1e04bd27910d06ced0205ee0864b56aa8ae7/Source/UserAgentParser.php#L148

Is this `!($key = 0)` ok?

**Comment by donatj** [comment]
Hmm… It looks like I was doing some sort of gross hack back in the day to lower the LoC.

I'll need to poke this a bit but it appears the tests pass when I remove it.

**Comment by donatj** [comment]
This was removed a while ago. 

Thank you for the heads up!

Closing.
