### ISSUE TITLE
No recognition of e-mail clients

### ISSUE THREAD

**Issue by AndrzejDunowski** [donatj/PhpUserAgent#53]
Very nice feature.

Unfortunately, he does not recognize e-mail clients.
I used this to track mailing openings by downloading a remote image and does not recognize anything.

Example User-Agent for Thunderbird
```
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Thunderbird/52.9.1 Lightning/5.4.9.1
```

For Gmail (by GoogleImagesProxy)
```
Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)
```

Thanks, Andrzej

**Comment by donatj** [comment]
I could potentially add support for Thunderbird as it follows the rules - I'm not 100% sure demand is there however. 

That given GoogleImageProxy ua-string on the other hand would likely require a special case for itself, and I don't think I can justify that.
