### ISSUE TITLE
Add user_agent initial string to output

### ISSUE THREAD

**Issue by sunnybear** [donatj/PhpUserAgent#55]
Please add user_agent key (with initial u_agent variable value) to return. It's usefull to operate with the whole object - initial string, platform, browser, version - to insert into DB rather than with 2 different variables, initial ua and user_agent array.

**Comment by donatj** [comment]
Assuming you are asking for the full original string as passed by the browser, can you not just read it from `$_SERVER['HTTP_USER_AGENT']` yourself?

**Comment by sunnybear** [comment]
Ok, good luck. It's quite convenient to have one array with all values instead of merging several arrays together. But as you wish.
