### ISSUE TITLE
Ruby port

### ISSUE THREAD

**Issue by luigifab38** [donatj/PhpUserAgent#57]
Hello all

I made a Ruby port of PhpUserAgent.
See [PHP version](https://gist.github.com/luigifab38/4cb373e75f3cd2f342ca6bc25504b149) and [Ruby version](https://gist.github.com/luigifab38/19a68d9aa98fa80f2961809d7cec59c0) (you can compare line by line).

Do as you want of this first version.

**Comment by donatj** [comment]
I only ask that as per the terms of the license, the license be included with the code.

https://github.com/donatj/PhpUserAgent/blob/master/LICENSE.md

**Comment by luigifab38** [comment]
That's true, I didn't see that your source file didn't include any notice. Added.
