### ISSUE TITLE
Opera Next

### ISSUE THREAD

**Issue by mark-wade** [donatj/PhpUserAgent#60]
Running the latest version of Opera on macOS has this user agent string:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 OPR/63.0.3368.94
```

Which is incorrectly being reported as "Opera Next" (Opera's beta version) rather than just "Opera".

**Comment by donatj** [comment]
They seemingly changed the method of detection, previously `OPR/*` differentiated Opera Next. It appears now they just append `(Edition beta)` to the end of the string.

I'm thinking I may just drop support for Opera Next, it doesn't seem worth the added overhead to detect separately from Opera.

**Comment by donatj** [comment]
I've gone ahead with that change and tagged a new release https://github.com/donatj/PhpUserAgent/releases/tag/v0.15.0
