### ISSUE TITLE
UC Browser not detected

### ISSUE THREAD

**Issue by infendory** [donatj/PhpUserAgent#63]
My Android UC Browser uses this UA string:
`Mozilla/5.0 (Linux; U; Android 6.0; en-US; ZTE BLADE V7 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/13.0.8.1291 Mobile Safari/537.36`

when passing this to parse_user_agent, the result is: 
Android/Chrome/57.0.2987.108

**Comment by donatj** [comment]
Thank you for the heads up. I corrected this and tagged a release v0.16.0 https://github.com/donatj/PhpUserAgent/releases/tag/v0.16.0
