### ISSUE TITLE
Googlebot Mobile not Detected

### ISSUE THREAD

**Issue by dutom007** [donatj/PhpUserAgent#72]
Hi,

For this user agent :
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.97 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

parse_user_agent() return :
browser => Chrome
platform => Android
version => 90.0.4430.97

**Comment by donatj** [comment]
Thank you for the report. I've already got my eye on a fix for `(compatible; ` user agents in general. This should probably give me the little bit of a push I need to actually do it.

**Comment by dutom007** [comment]
Great, happy to help :)
