### ISSUE TITLE
[New] Device Detector API Beats Regex Solutions

### ISSUE THREAD

**Issue by realtechspecs** [donatj/PhpUserAgent#80]
Hello Devs,

Detecting the device details of your users is now easier than ever with Detective API. Our API is powered by AI and makes detecting devices easy and effortless. [Check it out](https://techspecs.readme.io/reference/introducing-techspecs-detective)

**Comment by donatj** [comment]
Hey, please don't spam.

I can see you opened this exact same ticket on a bunch of repos. I'm sure they'll all be no more happy about it than I am.

https://github.com/issues?q=is%3Aopen+is%3Aissue+author%3Arealtechspecs

**Comment by realtechspecs** [comment]
> Hey, please don't spam.
> 
> I can see you opened this exact same ticket on a bunch of repos. I'm sure they'll all be no more happy about it than I am.
> 
> https://github.com/issues?q=is%3Aopen+is%3Aissue+author%3Arealtechspecs

No spam intended. We want to help you where we can.

We are excited to let you know that our API can handle all six of your currently open issues on this repo.

We'd like to explore a potential collaboration with you to integrate our API as a fallback to process strings that are currently too difficult for your library to handle. This will ensure that your repo remains healthy.
