### ISSUE TITLE
object mode

### ISSUE THREAD

**Issue by fernandosngular** [donatj/PhpUserAgent#91]
use donatj\UserAgent\UserAgentParser;

not working,
is namespace definition right?

**Comment by donatj** [comment]
The use is correct. It's useful when opening a ticket to provide context of what you are doing.

Are you using composer? Did you require the composer autoloader?

**Comment by donatj** [comment]
I've updated the example/README to show how to use composer if you are using composer.

**Comment by fernandosngular** [comment]
It is perfect
