### ISSUE TITLE
Can you add Korean Browser "Whale"?

### ISSUE THREAD

**Issue by zardsama** [donatj/PhpUserAgent#99]
- Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Whale/3.28.266.14 Safari/537.36

- Download Link
- https://whale.naver.com/ko/download/win/

Chrome Compatible

Thank you

**Comment by donatj** [comment]
Do you have any information on usage numbers or how popular it is in the Korean market

**Comment by zardsama** [comment]
In the Korean market, the wholesale browser marks the fourth-largest usage rate, and the usage rate is about 10%.
(9.17% as of 2022)
It is also planning to enter the world starting with Southeast Asia.

https://ko.wikipedia.org/wiki/%EB%84%A4%EC%9D%B4%EB%B2%84_%EC%9B%A8%EC%9D%BC

**Comment by donatj** [comment]
Those are about the numbers I was finding too. That is not insignificant. I will see about an update to support it soon!

**Comment by donatj** [comment]
https://github.com/donatj/PhpUserAgent/releases/tag/v1.10.0 is released, with Naver Whale support 🎉
